### ISSUE TITLE
File upload error when /tmp/ is in different partition?

### ISSUE THREAD

**Issue by f3rnando** [danzajdband/hackdash#52] opened 2013-07-22 19:11 UTC
> /uploads/e673582a2f0c205cd15ba9da125ef4da.png
> /tmp/e673582a2f0c205cd15ba9da125ef4da
> { [Error: EXDEV, rename '/tmp/e673582a2f0c205cd15ba9da125ef4da']
>   errno: 52,
>   code: 'EXDEV',
>   path: '/tmp/e673582a2f0c205cd15ba9da125ef4da' }

http://stackoverflow.com/questions/4568689/how-do-i-move-file-a-to-a-different-partition-or-device-in-node-js

**Comment by pjnovas** [comment] 2015-04-30 14:25
@f3rnando I'm closing, I couldn't reproduce it and it is too old.
Feel free to re-open if it happens again.

**Closed by pjnovas** 2015-04-30 14:25 UTC
Labels: bug
